### PR TITLE
Adding assertPropertyEntangled method and tests

### PR DESCRIPTION
**Pull request by cheesegrits**
Adding support for assertPropertyEntangled().  The weirdness with the htmlspecialchars() is for the corner case where the property is entangled inside of a JS function call inside x-data, in my case supporting an input masking plugin, at which point the quotes get encoded.

BTW, you might want to preg_quote $property everywhere it is used in RE's, otherwise dotted properties like user.name could match userXname.

And ... any chance you can merge #11 supporting single or double quotes?

### CODE REVIEW

**Comment by cheesegrits** [comment]
Crap, just noticed PHP Storm stripped the trailing spaces in the test component.  Let me know if you want me to undo that.

**Comment by christophrumpel** [comment]
Hey, thanks a lot for the PR. Looks good to me, can you just take care of the conflict? There was an older PR that I just merged before yours. The GH action should take care of the styles, so all good 👍

**Comment by cheesegrits** [comment]
Should be good to go.

**Comment by christophrumpel** [comment]
Thanks a lot @cheesegrits, nice addition!

**Pull request merged**
