### PR TITLE
Add IDE support for assertions

### PR DESCRIPTION
**Pull request by alexmanase**
Inspired by Filament (https://github.com/filamentphp/filament/blob/3.x/packages/actions/.stubs.php)

### CODE REVIEW

**Comment by christophrumpel** [comment]
Hey, thanks for the PR. How does that work?

**Comment by alexmanase** [comment]
Using bracketed namespaces you can basically "redeclare" the methods of a class.

**Comment by christophrumpel** [comment]
Nice, so people would get auto-completion without using Laravel Idea plugin?

**Comment by alexmanase** [comment]
That's right.

**Comment by christophrumpel** [comment]
Nice, thanks a lot 👍

**Pull request merged**
